/*
 * File: app/view/MyImage.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Movies.view.MyImage', {
    extend: 'Ext.Img',

    config: {
        height: 110,
        id: 'movieImage',
        itemId: 'movieImage',
        style: 'background-size: 65%; ',
        width: 159,
        src: ''
    }

});